#!/usr/bin/env python3
"""
SixZuper IG Edukasi - Dry Run Publisher
Simulates full publish flow without actual IG API calls.
Useful for staging/testing content pipeline.

Usage:
  python3 dry_run_publish.py --tip "Your tech tip here"
  python3 dry_run_publish.py --random-tip
"""
import json
import sys
import os
import argparse
import subprocess
from pathlib import Path
from datetime import datetime

# Add scripts directory to path
sys.path.insert(0, str(Path(__file__).parent))

# Load environment
def load_env():
    env = {}
    env_path = Path.home() / ".hermes" / ".env"
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    env[k.strip()] = v.strip()
    return env

def generate_quote_card(tip_text, source="Daily Tech Tip", output_dir="~/sixzuper-content/drafts"):
    """
    Simulate p5.js quote card generation by creating a placeholder image.
    In production: replace with actual p5.js headless render call.
    """
    import base64
    
    # Placeholder PNG (1080x1080 transparent)
    # This simulates what p5.js would produce
    placeholder_png = base64.b64decode(
        "iVBORw0KGgoAAAANSUhEUgAAAOAAAADgCAYAAAD..."
    ) if False else b"PLACEHOLDER_PNG_DATA"
    
    # For dry-run, generate a text-based preview instead
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"edu_post_{timestamp}.txt"
    filepath = Path(output_dir).expanduser() / filename
    filepath.parent.mkdir(parents=True, exist_ok=True)
    
    content = f"""
SIXZUPER DAILY TECH TIP
=======================

📝 Tip: {tip_text}

📅 Generated: {datetime.now().isoformat()}
📤 Status: [DRY RUN] - Ready for review
🎨 Format: 1080x1080 (Square Post)
🏷️ Hashtags: #TechTips #SixzuperLabs #LearnWithAI

This is a simulation file.
In production, this would be a PNG generated by p5.js.
"""
    
    with open(filepath, "w") as f:
        f.write(content)
    
    return str(filepath)

def simulate_cdn_upload(file_path):
    """Simulate uploading to CDN (GitHub Pages)."""
    # In dry-run mode, skip actual upload
    # Return simulated CDN URL
    filename = Path(file_path).name
    cdn_url = f"https://raw.githubusercontent.com/sixzuper/sixzuper-content/main/drafts/{filename}"
    return cdn_url, "simulated"

def build_caption(tip_text):
    """Build full Instagram caption with hashtags."""
    hashtags = [
        "#TechTips", "#SixzuperLabs", "#LearnWithAI",
        "#WebDev", "#Laravel", "#TechEducation"
    ]
    
    caption = f"""💡 SixZuper Daily Tech Tip

{tip_text}

.
.
.
#TechTips #SixzuperLabs #LearnWithAI #WebDev #Laravel"""
    
    return caption, hashtags

def log_post_attempt(caption, cdn_url, status="dry_run", notes=None):
    """Log post attempt to publish_log.jsonl."""
    log_path = Path.home() / "sixzuper-content" / "publish_log.jsonl"
    entry = {
        "timestamp": datetime.now().isoformat(),
        "caption_preview": caption[:100],
        "cdn_url": cdn_url,
        "status": status,
        "notes": notes or "Dry run simulation - no actual IG publish"
    }
    
    with open(log_path, "a") as f:
        f.write(json.dumps(entry) + "\n")
    
    return entry

def print_telegram_summary(tip_text, caption, cdn_url, filename):
    """Print summary suitable for Telegram delivery."""
    summary = f"""📸 SixZuper Edukasi Post Generator (DRY RUN)

📝 *Tech Tip:* `{tip_text}`

📎 *Generated File:* `{Path(filename).name}`
🔗 *Simulated CDN URL:* `{cdn_url}`
📅 *Schedule:* Tomorrow 07:00 WIB

📋 *Caption Preview:*
```
{caption[:200]}...
```

⚠️ *Status:* AWAITING_APPROVAL
Token pending Meta App Review — content staged for immediate publish upon approval.

_Auto-generated by Kilua — SixZuper Labs AI Agent_"""

    print("\n" + "="*60)
    print(summary)
    print("="*60)
    return summary

def main():
    parser = argparse.ArgumentParser(description="SixZuper IG Edukasi Dry Run Publisher")
    parser.add_argument("--tip", type=str, help="Custom tech tip text")
    parser.add_argument("--random-tip", action="store_true", help="Use random tip from database")
    
    args = parser.parse_args()
    
    # Load environment
    env = load_env()
    
    # Get tip text
    if args.tip:
        tip_text = args.tip
    elif args.random_tip:
        from tips_database import get_todays_tip
        tip_text = get_todays_tip()
    else:
        # Default fallback
        tip_text = "Gunakan .env untuk konfigurasi — jangan hardcoded values!"
    
    print(f"📝 Generating post for tip: {tip_text}")
    
    # Generate content
    output_file = generate_quote_card(tip_text)
    print(f"📤 Generated: {output_file}")
    
    # Simulate CDN upload
    cdn_url, upload_status = simulate_cdn_upload(output_file)
    print(f"📡 CDN URL: {cdn_url} ({upload_status})")
    
    # Build caption
    caption, hashtags = build_caption(tip_text)
    print(f"📄 Caption length: {len(caption)} chars")
    
    # Log attempt
    entry = log_post_attempt(caption, cdn_url)
    print(f"📝 Logged to publish_log.jsonl")
    
    # Print Telegram summary
    summary = print_telegram_summary(tip_text, caption, cdn_url, output_file)
    
    # Save summary for reference
    summary_path = Path(output_file).parent / f"summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(summary_path, "w") as f:
        json.dump({
            "tip": tip_text,
            "caption": caption,
            "cdn_url": cdn_url,
            "file_path": output_file,
            "hashtags": hashtags,
            "status": "dry_run",
            "timestamp": datetime.now().isoformat()
        }, f, indent=2)
    
    print(f"\n✅ Dry run complete. Files saved to {Path(output_file).parent}")

if __name__ == "__main__":
    main()